# .github/workflows/create-iso.yml

name: Create ISO and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release-iso:
    runs-on: ubuntu-latest

    steps:
      # 1. チェックアウト (変更なし)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. ツールをインストール (変更なし)
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y genisoimage

      # 3. ISOを作成 (変更なし)
      - name: Create ISO image
        run: mkisofs -o cdrom.iso -J -R iso_contents/
        
      # 4. リリースの作成とアップロード
      - name: Create or Update Release and Upload ISO
        # ▼▼▼ 変更点: このif条件を1行追加 ▼▼▼
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: cdrom.iso
