# .github/workflows/create-iso.yml

name: Create ISO and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release-iso:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのソースコードをチェックアウト (変更なし)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. ISO作成ツールをインストール (変更なし)
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y genisoimage

      # 3. cdrom.isoを作成 (変更なし)
      - name: Create ISO image
        run: mkisofs -o cdrom.iso -J -R iso_contents/
        
      # ▼▼▼ ここから下を変更 ▼▼▼
      # 4. リリースの作成とISOファイルのアップロードをまとめて実行
      - name: Create or Update Release and Upload ISO
        uses: softprops/action-gh-release@v2
        with:
          # 作成したISOファイルを指定します
          # 複数ある場合は改行して列挙できます
          files: cdrom.iso
